// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
require("./fonts.css");

export const accent = {
  fontFamily: "Inter",
  fontSize: "14px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "20px",
};
export const bodyLarge = {
  fontFamily: "Averta",
  fontSize: "24px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "24px",
};
export const bodyReallySmall = {
  fontFamily: "Averta",
  fontSize: "16px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "18px",
};
export const bodySmall = {
  fontFamily: "Averta",
  fontSize: "22px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "24px",
};
export const bodySmallBold = {
  fontFamily: "Averta",
  fontSize: "22px",
  fontWeight: 600,
  fontStyle: "normal",
  lineHeight: "23px",
};
export const bodySmallMobile = {
  fontFamily: "Averta",
  fontSize: "20px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "1",
};
export const hbFeatureText = {
  fontFamily: "Averta",
  fontSize: "16px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "21px",
};
export const hbFeatureTitle = {
  fontFamily: "Filson Pro",
  fontSize: "18px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "28px",
};
export const headSmall = {
  fontFamily: "Averta",
  fontSize: "22px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "20px",
};
export const heading = {
  fontFamily: "Inter",
  fontSize: "18px",
  fontWeight: 500,
  fontStyle: "normal",
  lineHeight: "26px",
};
export const menuHeading = {
  fontFamily: "Averta",
  fontSize: "15px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "1",
  textTransform: "uppercase",
};
export const menuHeadingTablet = {
  fontFamily: "Averta",
  fontSize: "13px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "1",
  textTransform: "uppercase",
};
export const superHeading = {
  fontFamily: "Filson Pro",
  fontSize: "32px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "48px",
};
export const superHeadingMobile = {
  fontFamily: "Averta",
  fontSize: "24px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "30px",
};
export const superHeadingTablet = {
  fontFamily: "Averta",
  fontSize: "28px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "1",
};
