// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export interface TextStyle {
  fontFamily: string;
  fontSize: string;
  fontWeight: number;
  fontStyle: string;
  lineHeight?: string;
}
export const accent: TextStyle;
export const bodyLarge: TextStyle;
export const bodySmall: TextStyle;
export const bodySmallBold: TextStyle;
export const heading: TextStyle;
