// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./CommentButton.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  SpacerPrimitive,
  TextPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import { ToggleButtonRoot } from "./_internal_togglebutton";

const styles = [
  {
    type: "default",
    layers: {
      "336oAbe272": {
        none: {
          text: "102",
        },
      },
      YLowiHcxUk: {
        none: {
          icon: require("./assets/c960c1cc-f05b-4842-972b-c497154e2e5b@1x.svg"),
          useMask: true,
        },
        hover: {
          useMask: true,
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {
      YLowiHcxUk: {
        none: {
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "checked",
  },
];

export const CommentButtonContext = createContext(null);

function CommentButton(_props) {
  const defaults = useContext(CommentButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ToggleButtonRoot
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "root",
        scope: "VgTPJAfPnx",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <IconPrimitive
            id={"icon_YLowiHcxUk"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_VgTPJAfPnx_YLowiHcxUk"
            }
            key={"YLowiHcxUk"}
            useMask={getStyle("YLowiHcxUk", "useMask")}
            src={
              exists(props.icon) ? props.icon : getStyle("YLowiHcxUk", "icon")
            }
          />
          <SpacerPrimitive
            id={"spacer_QqpfPi4ifo"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_VgTPJAfPnx_QqpfPi4ifo"
            }
            key={"QqpfPi4ifo"}
          />
          <TextPrimitive
            id={"text_336oAbe272"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_VgTPJAfPnx_336oAbe272"
            }
            key={"336oAbe272"}
            text={
              exists(props.text) ? props.text : getStyle("336oAbe272", "text")
            }
            element={getStyle("336oAbe272", "htmlElement")}
          />
        </>
      )}
    </ToggleButtonRoot>
  );
}

CommentButton.__variants = [
  {
    name: "checked",
    type: "variant",
  },
];

export default CommentButton;
