// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbButtonGroup.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ContainerPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbButtonGroupContext = createContext(null);

function HbButtonGroup(_props) {
  const defaults = useContext(HbButtonGroupContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="7Juzb2Pfn4"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "7Juzb2Pfn4",
        scope: "5cGf1BQia4",
        activeVariants: activeVariants,
      }}
    >
      <ContainerPrimitive
        key={"KYnFXgB8gr"}
        className={"__visly_reset __visly_scope_5cGf1BQia4_KYnFXgB8gr"}
        addSpacing={true}
      >
        {props.children}
      </ContainerPrimitive>
    </RootPrimitive>
  );
}

HbButtonGroup.__variants = [];

export default HbButtonGroup;
