// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbContent.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ContainerPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "enum",
    propName: "customProp",
    values: [
      {
        propValue: "small",
        layers: {},
      },
      {
        propValue: "medium",
        layers: {},
      },
      {
        propValue: "large",
        layers: {},
      },
      {
        propValue: "super",
        layers: {},
      },
    ],
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "enum",
    propName: "customProp",
    values: [
      {
        propValue: "small",
        layers: {},
      },
      {
        propValue: "medium",
        layers: {},
      },
      {
        propValue: "large",
        layers: {},
      },
      {
        propValue: "super",
        layers: {},
      },
    ],
  },
];

const variantPropTypes = [
  {
    type: "enum",
    propName: "customProp",
    propValues: ["small", "medium", "large", "super"],
  },
];

export const HbContentContext = createContext(null);

function HbContent(_props) {
  const defaults = useContext(HbContentContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="GWx7RTdU26"
      addSpacing={false}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "GWx7RTdU26",
        scope: "MgHA7CBn3d",
        activeVariants: activeVariants,
      }}
    >
      <ContainerPrimitive
        key={"863xCtrSQi"}
        id={"Slot_863xCtrSQi"}
        className={
          "__visly_reset_WDRq65T88Q __visly_scope_MgHA7CBn3d_863xCtrSQi"
        }
        addSpacing={true}
      >
        {props.children}
      </ContainerPrimitive>
    </RootPrimitive>
  );
}

HbContent.__variants = [
  {
    name: "customProp",
    type: "group",
    variants: ["small", "medium", "large", "super"],
  },
];

export default HbContent;
