// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbFirstSlideFooter.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive } from "./_internal_primitives";
import HbFooterRectangleComposite, {
  HbFooterRectangleContext,
} from "./HbFooterRectangle";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "medium",
        layers: {},
      },
      {
        propValue: "large",
        layers: {},
      },
    ],
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      TNW5v7g5Qv: {
        none: {
          icon: require("./assets/886449e4-75e9-407f-b77d-2de8cc4a0895.svg"),
          title: "Super premium ingredients",
          subtitle: "Made with real meat and superfoods.",
        },
      },
      SV2fibrpk9: {
        none: {
          icon: require("./assets/dbe16c81-bff3-4c34-a2cf-276c5ce67996.png"),
          title: "Vet approved",
          subtitle: "Shop with confidence",
        },
      },
      "4Lgg4oSHk1": {
        none: {
          icon: require("./assets/3421457c-3753-4949-b709-b4d47224a029.svg"),
          title: "Custom nutrition",
          subtitle: "Personalized plan for your dog",
        },
      },
    },
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "medium",
        layers: {
          TNW5v7g5Qv: {
            none: {
              size: "medium",
            },
          },
          SV2fibrpk9: {
            none: {
              size: "medium",
            },
          },
          "4Lgg4oSHk1": {
            none: {
              size: "medium",
            },
          },
        },
      },
      {
        propValue: "large",
        layers: {
          TNW5v7g5Qv: {
            none: {
              size: "large",
            },
          },
          SV2fibrpk9: {
            none: {
              size: "large",
            },
          },
          "4Lgg4oSHk1": {
            none: {
              size: "large",
            },
          },
        },
      },
    ],
  },
];

const variantPropTypes = [
  {
    type: "enum",
    propName: "size",
    propValues: ["medium", "large"],
  },
];

export const HbFirstSlideFooterContext = createContext(null);

function HbFirstSlideFooter(_props) {
  const defaults = useContext(HbFirstSlideFooterContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="FSzKVGr5cz"
      addSpacing={true}
      internal={{
        styles: styles,
        layerId: "FSzKVGr5cz",
        scope: "Mdjkh2vofL",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.HbFooterRectangle === undefined ? (
          <HbFooterRectangleComposite
            key={"TNW5v7g5Qv"}
            {...getCompositeDefaultProps("TNW5v7g5Qv")}
            className="__visly_reset __visly_scope_Mdjkh2vofL_TNW5v7g5Qv"
          />
        ) : (
          <HbFooterRectangleContext.Provider
            key="TNW5v7g5Qv-provider"
            value={{
              key: "TNW5v7g5Qv",
              className: "__visly_reset __visly_scope_Mdjkh2vofL_TNW5v7g5Qv",
              ...getCompositeDefaultProps("TNW5v7g5Qv"),
            }}
          >
            {props.HbFooterRectangle}
          </HbFooterRectangleContext.Provider>
        ),
        props.HbFooterRectangle1 === undefined ? (
          <HbFooterRectangleComposite
            key={"SV2fibrpk9"}
            {...getCompositeDefaultProps("SV2fibrpk9")}
            className="__visly_reset __visly_scope_Mdjkh2vofL_SV2fibrpk9"
          />
        ) : (
          <HbFooterRectangleContext.Provider
            key="SV2fibrpk9-provider"
            value={{
              key: "SV2fibrpk9",
              className: "__visly_reset __visly_scope_Mdjkh2vofL_SV2fibrpk9",
              ...getCompositeDefaultProps("SV2fibrpk9"),
            }}
          >
            {props.HbFooterRectangle1}
          </HbFooterRectangleContext.Provider>
        ),
        props.HbFooterRectangle2 === undefined ? (
          <HbFooterRectangleComposite
            key={"4Lgg4oSHk1"}
            {...getCompositeDefaultProps("4Lgg4oSHk1")}
            className="__visly_reset __visly_scope_Mdjkh2vofL_4Lgg4oSHk1"
          />
        ) : (
          <HbFooterRectangleContext.Provider
            key="4Lgg4oSHk1-provider"
            value={{
              key: "4Lgg4oSHk1",
              className: "__visly_reset __visly_scope_Mdjkh2vofL_4Lgg4oSHk1",
              ...getCompositeDefaultProps("4Lgg4oSHk1"),
            }}
          >
            {props.HbFooterRectangle2}
          </HbFooterRectangleContext.Provider>
        ),
      ]}
    </RootPrimitive>
  );
}

HbFirstSlideFooter.HbFooterRectangle = HbFooterRectangleComposite;
HbFirstSlideFooter.HbFooterRectangle1 = HbFooterRectangleComposite;
HbFirstSlideFooter.HbFooterRectangle2 = HbFooterRectangleComposite;
HbFirstSlideFooter.__variants = [
  {
    name: "size",
    type: "group",
    variants: ["medium", "large"],
  },
];

export default HbFirstSlideFooter;
