// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbHeader.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "./_internal_primitives";
import HbCircleIconComposite, { HbCircleIconContext } from "./HbCircleIcon";
import HbProgressComposite, { HbProgressContext } from "./HbProgress";
import HbLogoComposite, { HbLogoContext } from "./HbLogo";

const styles = [
  {
    type: "default",
    layers: {
      "2RwNh3KRbg": {
        none: {
          htmlElement: "header",
        },
      },
      WVr4DnUAPt: {
        none: {
          text: "20% Off",
        },
      },
      GJpwns7nhj: {
        none: {
          text: "$50+ Ships Free",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "NoWave",
    layers: {},
  },
  {
    type: "boolean",
    propName: "withVideo",
    layers: {},
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "small",
        layers: {},
      },
      {
        propValue: "medium",
        layers: {
          "2RwNh3KRbg": {
            none: {
              htmlElement: "header",
            },
          },
        },
      },
      {
        propValue: "super",
        layers: {},
      },
    ],
  },
  {
    type: "boolean",
    propName: "ShowImage",
    layers: {},
  },
  {
    type: "boolean",
    propName: "noTitleNoSubtitle",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      Coy4GvRJN5: {
        none: {
          icon: require("./assets/6c09c43b-abd0-4776-8845-1535cdff712b.svg"),
          HbYellowIcon: true,
        },
      },
      B28tWsTkne: {},
      DesmwGXXNp: {},
      "9VxZfYB53B": {},
    },
  },
  {
    type: "boolean",
    propName: "NoWave",
    layers: {
      Coy4GvRJN5: {},
      B28tWsTkne: {},
      DesmwGXXNp: {},
      "9VxZfYB53B": {},
    },
  },
  {
    type: "boolean",
    propName: "withVideo",
    layers: {
      Coy4GvRJN5: {},
      B28tWsTkne: {},
      DesmwGXXNp: {},
      "9VxZfYB53B": {},
    },
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "small",
        layers: {
          Coy4GvRJN5: {
            none: {
              size: "small",
            },
          },
          B28tWsTkne: {},
          DesmwGXXNp: {
            none: {
              size: "small",
            },
          },
          "9VxZfYB53B": {},
        },
      },
      {
        propValue: "medium",
        layers: {
          Coy4GvRJN5: {},
          B28tWsTkne: {},
          DesmwGXXNp: {},
          "9VxZfYB53B": {},
        },
      },
      {
        propValue: "super",
        layers: {
          Coy4GvRJN5: {},
          B28tWsTkne: {},
          DesmwGXXNp: {},
          "9VxZfYB53B": {},
        },
      },
    ],
  },
  {
    type: "boolean",
    propName: "ShowImage",
    layers: {
      Coy4GvRJN5: {},
      B28tWsTkne: {},
      DesmwGXXNp: {},
      "9VxZfYB53B": {},
    },
  },
  {
    type: "boolean",
    propName: "noTitleNoSubtitle",
    layers: {
      Coy4GvRJN5: {},
      B28tWsTkne: {},
      DesmwGXXNp: {},
      "9VxZfYB53B": {},
    },
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "NoWave",
  },
  {
    type: "boolean",
    propName: "withVideo",
  },
  {
    type: "enum",
    propName: "size",
    propValues: ["small", "medium", "super"],
  },
  {
    type: "boolean",
    propName: "ShowImage",
  },
  {
    type: "boolean",
    propName: "noTitleNoSubtitle",
  },
];

export const HbHeaderContext = createContext(null);

function HbHeader(_props) {
  const defaults = useContext(HbHeaderContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="MPFekVRp85"
      addSpacing={false}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "MPFekVRp85",
        scope: "9XVkrqrLZt",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            id={"Background Layer_7zMWCZsd7M"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_7zMWCZsd7M"
            }
            key={"7zMWCZsd7M"}
            addSpacing={false}
            element={getStyle("7zMWCZsd7M", "htmlElement")}
            style={{
              position: "absolute",
            }}
          >
            {
              <ImagePrimitive
                id={"Image_GPsUKuwC2X"}
                className={
                  "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_GPsUKuwC2X"
                }
                key={"GPsUKuwC2X"}
                src={
                  exists(props.bg) ? props.bg : getStyle("GPsUKuwC2X", "src")
                }
                alt={getStyle("GPsUKuwC2X", "alternateText")}
              />
            }
          </ContainerPrimitive>
          <ContainerPrimitive
            id={"HbContainer_47pNJ4CTVs"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_47pNJ4CTVs"
            }
            key={"47pNJ4CTVs"}
            addSpacing={true}
            element={getStyle("47pNJ4CTVs", "htmlElement")}
          >
            <ContainerPrimitive
              id={"ExtraImg_5dTrnoEMCT"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_5dTrnoEMCT"
              }
              key={"5dTrnoEMCT"}
              addSpacing={true}
              element={getStyle("5dTrnoEMCT", "htmlElement")}
              style={{
                position: "absolute",
              }}
            >
              {
                <ImagePrimitive
                  id={"Image_CdpiHELTSf"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_CdpiHELTSf"
                  }
                  key={"CdpiHELTSf"}
                  src={
                    exists(props.extraImage)
                      ? props.extraImage
                      : getStyle("CdpiHELTSf", "src")
                  }
                  alt={getStyle("CdpiHELTSf", "alternateText")}
                />
              }
            </ContainerPrimitive>
            <ContainerPrimitive
              id={"Head_BvQJi9KfB1"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_BvQJi9KfB1"
              }
              key={"BvQJi9KfB1"}
              addSpacing={true}
              element={getStyle("BvQJi9KfB1", "htmlElement")}
            >
              {[
                <ContainerPrimitive
                  id={"HbLogoContainer_MCEaYWZj8Y"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_MCEaYWZj8Y"
                  }
                  key={"MCEaYWZj8Y"}
                  addSpacing={false}
                  element={getStyle("MCEaYWZj8Y", "htmlElement")}
                >
                  {props.HbLogo === undefined ? (
                    <HbLogoComposite
                      key={"DesmwGXXNp"}
                      {...getCompositeDefaultProps("DesmwGXXNp")}
                      id="HbLogo_DesmwGXXNp"
                      className="__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_DesmwGXXNp"
                    />
                  ) : (
                    <HbLogoContext.Provider
                      key="DesmwGXXNp-provider"
                      value={{
                        key: "DesmwGXXNp",
                        id: "HbLogo_DesmwGXXNp",
                        className:
                          "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_DesmwGXXNp",
                        ...getCompositeDefaultProps("DesmwGXXNp"),
                      }}
                    >
                      {props.HbLogo}
                    </HbLogoContext.Provider>
                  )}
                </ContainerPrimitive>,
                props.HbProgress === undefined ? (
                  <HbProgressComposite
                    key={"B28tWsTkne"}
                    {...getCompositeDefaultProps("B28tWsTkne")}
                    id="HbProgress_B28tWsTkne"
                    className="__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_B28tWsTkne"
                  />
                ) : (
                  <HbProgressContext.Provider
                    key="B28tWsTkne-provider"
                    value={{
                      key: "B28tWsTkne",
                      id: "HbProgress_B28tWsTkne",
                      className:
                        "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_B28tWsTkne",
                      ...getCompositeDefaultProps("B28tWsTkne"),
                    }}
                  >
                    {props.HbProgress}
                  </HbProgressContext.Provider>
                ),
                <ContainerPrimitive
                  id={"Row_UG6YPtbpZv"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_UG6YPtbpZv"
                  }
                  key={"UG6YPtbpZv"}
                  addSpacing={false}
                  element={getStyle("UG6YPtbpZv", "htmlElement")}
                >
                  {[
                    props.HbCircleIcon === undefined ? (
                      <HbCircleIconComposite
                        key={"Coy4GvRJN5"}
                        {...getCompositeDefaultProps("Coy4GvRJN5")}
                        id="HbCircleIcon_Coy4GvRJN5"
                        className="__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_Coy4GvRJN5"
                      />
                    ) : (
                      <HbCircleIconContext.Provider
                        key="Coy4GvRJN5-provider"
                        value={{
                          key: "Coy4GvRJN5",
                          id: "HbCircleIcon_Coy4GvRJN5",
                          className:
                            "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_Coy4GvRJN5",
                          ...getCompositeDefaultProps("Coy4GvRJN5"),
                        }}
                      >
                        {props.HbCircleIcon}
                      </HbCircleIconContext.Provider>
                    ),
                    <SpacerPrimitive
                      id={"Spacer_4vbMB4cs8F"}
                      className={
                        "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_4vbMB4cs8F"
                      }
                      key={"4vbMB4cs8F"}
                    />,
                    <ContainerPrimitive
                      id={"Column_8Y3DCw5uX1"}
                      className={
                        "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_8Y3DCw5uX1"
                      }
                      key={"8Y3DCw5uX1"}
                      addSpacing={false}
                      element={getStyle("8Y3DCw5uX1", "htmlElement")}
                    >
                      <TextPrimitive
                        id={"Text_WVr4DnUAPt"}
                        className={
                          "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_WVr4DnUAPt"
                        }
                        key={"WVr4DnUAPt"}
                        text={
                          exists(props.discount)
                            ? props.discount
                            : getStyle("WVr4DnUAPt", "text")
                        }
                        element={getStyle("WVr4DnUAPt", "htmlElement")}
                      />
                      <TextPrimitive
                        id={"Text_GJpwns7nhj"}
                        className={
                          "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_GJpwns7nhj"
                        }
                        key={"GJpwns7nhj"}
                        text={
                          exists(props.discount2)
                            ? props.discount2
                            : getStyle("GJpwns7nhj", "text")
                        }
                        element={getStyle("GJpwns7nhj", "htmlElement")}
                      />
                    </ContainerPrimitive>,
                  ]}
                </ContainerPrimitive>,
              ]}
            </ContainerPrimitive>
            <SpacerPrimitive
              id={"Spacer_FzQE2ekJkE"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_FzQE2ekJkE"
              }
              key={"FzQE2ekJkE"}
            />
            <ContainerPrimitive
              id={"ProgressMobile_DXVbq46P3D"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_DXVbq46P3D"
              }
              key={"DXVbq46P3D"}
              addSpacing={false}
              element={getStyle("DXVbq46P3D", "htmlElement")}
            >
              {props.HbProgressMobile === undefined ? (
                <HbProgressComposite
                  key={"9VxZfYB53B"}
                  {...getCompositeDefaultProps("9VxZfYB53B")}
                  id="HbProgressMobile_9VxZfYB53B"
                  className="__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_9VxZfYB53B"
                />
              ) : (
                <HbProgressContext.Provider
                  key="9VxZfYB53B-provider"
                  value={{
                    key: "9VxZfYB53B",
                    id: "HbProgressMobile_9VxZfYB53B",
                    className:
                      "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_9VxZfYB53B",
                    ...getCompositeDefaultProps("9VxZfYB53B"),
                  }}
                >
                  {props.HbProgressMobile}
                </HbProgressContext.Provider>
              )}
            </ContainerPrimitive>
            <SpacerPrimitive
              id={"Spacer_LHD69MvEi8"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_LHD69MvEi8"
              }
              key={"LHD69MvEi8"}
            />
            <ContainerPrimitive
              id={"Row_Ajq15sbMPw"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_Ajq15sbMPw"
              }
              key={"Ajq15sbMPw"}
              addSpacing={false}
              element={getStyle("Ajq15sbMPw", "htmlElement")}
            >
              <SpacerPrimitive
                id={"Spacer_AmuT4WgaTf"}
                className={
                  "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_AmuT4WgaTf"
                }
                key={"AmuT4WgaTf"}
              />
              <ContainerPrimitive
                id={"HbContent_2RwNh3KRbg"}
                className={
                  "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_2RwNh3KRbg"
                }
                key={"2RwNh3KRbg"}
                addSpacing={true}
                element={getStyle("2RwNh3KRbg", "htmlElement")}
              >
                <ContainerPrimitive
                  key={"VTKN5tHTts"}
                  id={"Slot_VTKN5tHTts"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_VTKN5tHTts"
                  }
                  addSpacing={false}
                >
                  {props.TitleSlot}
                </ContainerPrimitive>
                <ContainerPrimitive
                  key={"7hnTiRDRyn"}
                  id={"Slot_7hnTiRDRyn"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_7hnTiRDRyn"
                  }
                  addSpacing={false}
                >
                  {props.SubtitleSlot}
                </ContainerPrimitive>
                <SpacerPrimitive
                  id={"Spacer_JttkhPdb2e"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_JttkhPdb2e"
                  }
                  key={"JttkhPdb2e"}
                />
              </ContainerPrimitive>
              <ContainerPrimitive
                id={"Overlay_kUjGG71oGb"}
                className={
                  "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_kUjGG71oGb"
                }
                key={"kUjGG71oGb"}
                addSpacing={false}
                element={getStyle("kUjGG71oGb", "htmlElement")}
                style={{
                  position: "absolute",
                }}
              >
                {
                  <ImagePrimitive
                    id={"Image_AFED7U3hCF"}
                    className={
                      "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_AFED7U3hCF"
                    }
                    key={"AFED7U3hCF"}
                    src={
                      exists(props.extraImageT)
                        ? props.extraImageT
                        : getStyle("AFED7U3hCF", "src")
                    }
                    alt={getStyle("AFED7U3hCF", "alternateText")}
                  />
                }
              </ContainerPrimitive>
            </ContainerPrimitive>
            <ContainerPrimitive
              key={"47pCh1HY9f"}
              id={"Slot_47pCh1HY9f"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_9XVkrqrLZt_47pCh1HY9f"
              }
              addSpacing={false}
            >
              {props.ExtraChildren}
            </ContainerPrimitive>
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

HbHeader.HbCircleIcon = HbCircleIconComposite;
HbHeader.HbProgress = HbProgressComposite;
HbHeader.HbLogo = HbLogoComposite;
HbHeader.HbProgressMobile = HbProgressComposite;
HbHeader.__variants = [
  {
    name: "NoWave",
    type: "variant",
  },
  {
    name: "withVideo",
    type: "variant",
  },
  {
    name: "size",
    type: "group",
    variants: ["small", "medium", "super"],
  },
  {
    name: "ShowImage",
    type: "variant",
  },
  {
    name: "noTitleNoSubtitle",
    type: "variant",
  },
];

export default HbHeader;
