// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbKibblePlan.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive } from "./_internal_primitives";
import HbKibblePlanElementComposite, {
  HbKibblePlanElementContext,
} from "./HbKibblePlanElement";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      BAPwEtimG9: {},
      WJES13sMaW: {
        none: {
          icon: require("./assets/c7f2b5ef-b85b-4b85-81f7-02ecbb988bc7.svg"),
        },
      },
      BshJUS7w9H: {
        none: {
          icon: require("./assets/0c4feb96-1711-4d12-950a-0b305cfbe2e8.svg"),
          NoNext: true,
        },
      },
    },
  },
];

const variantPropTypes = [];

export const HbKibblePlanContext = createContext(null);

function HbKibblePlan(_props) {
  const defaults = useContext(HbKibblePlanContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="PjnQCuWtE6"
      addSpacing={true}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "PjnQCuWtE6",
        scope: "4manc1ULFQ",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.HbKibblePlanElement === undefined ? (
          <HbKibblePlanElementComposite
            key={"BAPwEtimG9"}
            {...getCompositeDefaultProps("BAPwEtimG9")}
            id="HbKibblePlanElement_BAPwEtimG9"
            className="__visly_reset_WDRq65T88Q __visly_scope_4manc1ULFQ_BAPwEtimG9"
          />
        ) : (
          <HbKibblePlanElementContext.Provider
            key="BAPwEtimG9-provider"
            value={{
              key: "BAPwEtimG9",
              id: "HbKibblePlanElement_BAPwEtimG9",
              className:
                "__visly_reset_WDRq65T88Q __visly_scope_4manc1ULFQ_BAPwEtimG9",
              ...getCompositeDefaultProps("BAPwEtimG9"),
            }}
          >
            {props.HbKibblePlanElement}
          </HbKibblePlanElementContext.Provider>
        ),
        props.HbKibblePlanElement1 === undefined ? (
          <HbKibblePlanElementComposite
            key={"WJES13sMaW"}
            {...getCompositeDefaultProps("WJES13sMaW")}
            id="HbKibblePlanElement1_WJES13sMaW"
            className="__visly_reset_WDRq65T88Q __visly_scope_4manc1ULFQ_WJES13sMaW"
          />
        ) : (
          <HbKibblePlanElementContext.Provider
            key="WJES13sMaW-provider"
            value={{
              key: "WJES13sMaW",
              id: "HbKibblePlanElement1_WJES13sMaW",
              className:
                "__visly_reset_WDRq65T88Q __visly_scope_4manc1ULFQ_WJES13sMaW",
              ...getCompositeDefaultProps("WJES13sMaW"),
            }}
          >
            {props.HbKibblePlanElement1}
          </HbKibblePlanElementContext.Provider>
        ),
        props.HbKibblePlanElement2 === undefined ? (
          <HbKibblePlanElementComposite
            key={"BshJUS7w9H"}
            {...getCompositeDefaultProps("BshJUS7w9H")}
            id="HbKibblePlanElement2_BshJUS7w9H"
            className="__visly_reset_WDRq65T88Q __visly_scope_4manc1ULFQ_BshJUS7w9H"
          />
        ) : (
          <HbKibblePlanElementContext.Provider
            key="BshJUS7w9H-provider"
            value={{
              key: "BshJUS7w9H",
              id: "HbKibblePlanElement2_BshJUS7w9H",
              className:
                "__visly_reset_WDRq65T88Q __visly_scope_4manc1ULFQ_BshJUS7w9H",
              ...getCompositeDefaultProps("BshJUS7w9H"),
            }}
          >
            {props.HbKibblePlanElement2}
          </HbKibblePlanElementContext.Provider>
        ),
      ]}
    </RootPrimitive>
  );
}

HbKibblePlan.HbKibblePlanElement = HbKibblePlanElementComposite;
HbKibblePlan.HbKibblePlanElement1 = HbKibblePlanElementComposite;
HbKibblePlan.HbKibblePlanElement2 = HbKibblePlanElementComposite;
HbKibblePlan.__variants = [];

export default HbKibblePlan;
