// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbPopover.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { TextPrimitive } from "./_internal_primitives";
import { PopoverRoot } from "./_internal_popover";

const styles = [
  {
    type: "default",
    layers: {
      "2nxKs2aETh": {
        none: {
          text: "This is a popover",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbPopoverContext = createContext(null);

function HbPopover(_props) {
  const defaults = useContext(HbPopoverContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <PopoverRoot
      {...props}
      key="popover-root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "popover-root",
        scope: "VMTpFDHeuv",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <TextPrimitive
          className={"__visly_reset __visly_scope_VMTpFDHeuv_2nxKs2aETh"}
          key={"2nxKs2aETh"}
          text={getStyle("2nxKs2aETh", "text")}
        />
      )}
    </PopoverRoot>
  );
}

HbPopover.__variants = [];

export default HbPopover;
