// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbSelect.Option.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { TextPrimitive } from "./_internal_primitives";
import { SelectOptionRoot } from "./_internal_select";

const styles = [
  {
    type: "default",
    layers: {
      Tas2nBSZkf: {
        none: {
          text: "Option",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "selected",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "selected",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "selected",
  },
];

export const OptionContext = createContext(null);

function Option(_props) {
  const defaults = useContext(OptionContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <SelectOptionRoot
      {...props}
      key="select-option-root"
      addSpacing={false}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "select-option-root",
        scope: "3kNAjMriiT",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <TextPrimitive
          id={"text_Tas2nBSZkf"}
          className={
            "__visly_reset_WDRq65T88Q __visly_scope_3kNAjMriiT_Tas2nBSZkf"
          }
          key={"Tas2nBSZkf"}
          text={
            exists(props.label) ? props.label : getStyle("Tas2nBSZkf", "text")
          }
          element={getStyle("Tas2nBSZkf", "htmlElement")}
        />
      )}
    </SelectOptionRoot>
  );
}

Option.__variants = [
  {
    name: "selected",
    type: "variant",
  },
];

export default Option;
