// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./HbWave.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  ContainerPrimitive,
  IconPrimitive,
} from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      Pvi6YdPjgx: {
        none: {
          role: "img",
          src: require("./assets/39bdde3d-e340-41ab-a8c8-5499642106d5.svg"),
          useMask: true,
        },
      },
      TGjmjt52AW: {
        none: {
          role: "img",
          src: require("./assets/39bdde3d-e340-41ab-a8c8-5499642106d5.svg"),
          useMask: true,
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "double",
    layers: {},
  },
  {
    type: "boolean",
    propName: "invert",
    layers: {},
  },
  {
    type: "boolean",
    propName: "dark",
    layers: {
      Pvi6YdPjgx: {
        none: {
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "double",
    layers: {},
  },
  {
    type: "boolean",
    propName: "invert",
    layers: {},
  },
  {
    type: "boolean",
    propName: "dark",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "double",
  },
  {
    type: "boolean",
    propName: "invert",
  },
  {
    type: "boolean",
    propName: "dark",
  },
];

export const HbWaveContext = createContext(null);

function HbWave(_props) {
  const defaults = useContext(HbWaveContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="G1EfLQfWP6"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "G1EfLQfWP6",
        scope: "RtitAK5Bpp",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_RtitAK5Bpp_EeCGBQ8FkZ"}
            key={"EeCGBQ8FkZ"}
            addSpacing={false}
          >
            {
              <IconPrimitive
                className={"__visly_reset __visly_scope_RtitAK5Bpp_TGjmjt52AW"}
                key={"TGjmjt52AW"}
                useMask={getStyle("TGjmjt52AW", "useMask")}
                src={getStyle("TGjmjt52AW", "src")}
              />
            }
          </ContainerPrimitive>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_RtitAK5Bpp_91q2eiiHtA"}
            key={"91q2eiiHtA"}
            addSpacing={false}
          >
            {
              <IconPrimitive
                className={"__visly_reset __visly_scope_RtitAK5Bpp_Pvi6YdPjgx"}
                key={"Pvi6YdPjgx"}
                useMask={getStyle("Pvi6YdPjgx", "useMask")}
                src={getStyle("Pvi6YdPjgx", "src")}
              />
            }
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

HbWave.__variants = [
  {
    name: "double",
    type: "variant",
  },
  {
    name: "invert",
    type: "variant",
  },
  {
    name: "dark",
    type: "variant",
  },
];

export default HbWave;
