// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "./textstyles/fonts.css";
import "./reset.css";
import "./Select.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  SpacerPrimitive,
  TextPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import {
  SelectRoot,
  SelectOptionContainer,
  SelectButton,
} from "./_internal_select";

const styles = [
  {
    type: "default",
    layers: {
      "select-button-text": {
        none: {
          text: "Selected",
        },
      },
      "2pmEsZq6Nc": {
        none: {
          role: "img",
          icon: require("./assets/c6f11592-eb2a-4697-9b7c-6c7c31b99f89@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const SelectContext = createContext(null);

function Select(_props) {
  const defaults = useContext(SelectContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <SelectRoot
      {...props}
      key="select-root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "select-root",
        scope: "9cCvR1MveE",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <SelectButton
            key="select-button"
            className="__visly_reset __visly_scope_9cCvR1MveE_select-button"
          >
            <TextPrimitive
              className={
                "__visly_reset __visly_scope_9cCvR1MveE_select-button-text"
              }
              key={"select-button-text"}
              text={
                exists(props.label)
                  ? props.label
                  : getStyle("select-button-text", "text")
              }
              element={getStyle("select-button-text", "htmlElement")}
            />
            <SpacerPrimitive
              className={"__visly_reset __visly_scope_9cCvR1MveE_XD9syCR31b"}
              key={"XD9syCR31b"}
            />
            <IconPrimitive
              className={"__visly_reset __visly_scope_9cCvR1MveE_2pmEsZq6Nc"}
              key={"2pmEsZq6Nc"}
              useMask={getStyle("2pmEsZq6Nc", "useMask")}
              src={getStyle("2pmEsZq6Nc", "icon")}
            />
          </SelectButton>
          <SelectOptionContainer
            key="select-menu"
            className="__visly_reset __visly_scope_9cCvR1MveE_select-menu"
            innerKey="select-menu"
            addSpacing={false}
            useButtonWidth={true}
          >
            {props.children}
          </SelectOptionContainer>
        </>
      )}
    </SelectRoot>
  );
}

Select.__variants = [];

export default Select;
