// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const hbCardShadow = "0px 2px 16px 0px rgba(0,0,0,0.1)";
export const hbFooterShadow = "0px 2px 4px 0px rgba(0,0,0,0.2)";
export const hbGoldenShadow = "0px 2px 4px 0px rgba(0,0,0,0.2)";
