// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const hbCardShadow: string;
export const hbFooterShadow: string;
export const hbGoldenShadow: string;
