// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const dimensions = {
  logoSize: "196px",
};
export const radius = {
  hbRadius: "4px",
};
export const spacing = {
  hbFooterSize: "100px",
};
