// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./Avatar.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ImagePrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      D7PGbZZgp4: {
        none: {
          alternateText: "Avatar",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const AvatarContext = createContext(null);

function Avatar(_props) {
  const defaults = useContext(AvatarContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="oFHs7Qk4Eu"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "oFHs7Qk4Eu",
        scope: "3ZeWAafJqb",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ImagePrimitive
          className={"__visly_reset __visly_scope_3ZeWAafJqb_D7PGbZZgp4"}
          key={"D7PGbZZgp4"}
          src={exists(props.src) ? props.src : getStyle("D7PGbZZgp4", "src")}
          alt={getStyle("D7PGbZZgp4", "alternateText")}
        />
      )}
    </RootPrimitive>
  );
}

Avatar.__variants = [];

export default Avatar;
