// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbContent.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ContainerPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbContentContext = createContext(null);

function HbContent(_props) {
  const defaults = useContext(HbContentContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="GWx7RTdU26"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "GWx7RTdU26",
        scope: "MgHA7CBn3d",
        activeVariants: activeVariants,
      }}
    >
      <ContainerPrimitive
        key={"863xCtrSQi"}
        className={"__visly_reset __visly_scope_MgHA7CBn3d_863xCtrSQi"}
        addSpacing={true}
      >
        {props.children}
      </ContainerPrimitive>
    </RootPrimitive>
  );
}

HbContent.__variants = [];

export default HbContent;
