// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbHelper.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { ListboxPrimitive } from "./_internal_listbox";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbHelperContext = createContext(null);

function HbHelper(_props) {
  const defaults = useContext(HbHelperContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ListboxPrimitive
      {...props}
      key="listbox-root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "listbox-root",
        scope: "SaVAXtyYQ8",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => props.children}
    </ListboxPrimitive>
  );
}

HbHelper.__variants = [];

export default HbHelper;
