// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbHeader.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive } from "./_internal_primitives";
import HbLogoComposite, { HbLogoContext } from "./HbLogo";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      DesmwGXXNp: {},
    },
  },
];

const variantPropTypes = [];

export const HbHeaderContext = createContext(null);

function HbHeader(_props) {
  const defaults = useContext(HbHeaderContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="MPFekVRp85"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "MPFekVRp85",
        scope: "9XVkrqrLZt",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) =>
        props.HbLogo === undefined ? (
          <HbLogoComposite
            key={"DesmwGXXNp"}
            {...getCompositeDefaultProps("DesmwGXXNp")}
            className="__visly_reset __visly_scope_9XVkrqrLZt_DesmwGXXNp"
          />
        ) : (
          <HbLogoContext.Provider
            key="DesmwGXXNp-provider"
            value={{
              key: "DesmwGXXNp",
              className: "__visly_reset __visly_scope_9XVkrqrLZt_DesmwGXXNp",
              ...getCompositeDefaultProps("DesmwGXXNp"),
            }}
          >
            {props.HbLogo}
          </HbLogoContext.Provider>
        )
      }
    </RootPrimitive>
  );
}

HbHeader.HbLogo = HbLogoComposite;
HbHeader.__variants = [];

export default HbHeader;
