// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbLogo.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, IconPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      FLHNXYLopv: {
        none: {
          role: "img",
          src: require("../assets/a5992a54-5d1a-4992-af21-8bf2fbbf0184.svg"),
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbLogoContext = createContext(null);

function HbLogo(_props) {
  const defaults = useContext(HbLogoContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="RuuCtDNuhF"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "RuuCtDNuhF",
        scope: "3udiZxmptc",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <IconPrimitive
          className={"__visly_reset __visly_scope_3udiZxmptc_FLHNXYLopv"}
          key={"FLHNXYLopv"}
          useMask={getStyle("FLHNXYLopv", "useMask")}
          src={getStyle("FLHNXYLopv", "src")}
        />
      )}
    </RootPrimitive>
  );
}

HbLogo.__variants = [];

export default HbLogo;
