// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbProgressButton.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { ButtonRoot } from "./_internal_button";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "HbProgressButtonActive",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "HbProgressButtonActive",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "HbProgressButtonActive",
  },
];

export const HbProgressButtonContext = createContext(null);

function HbProgressButton(_props) {
  const defaults = useContext(HbProgressButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ButtonRoot
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "root",
        scope: "LVXvoJHS2N",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => null}
    </ButtonRoot>
  );
}

HbProgressButton.__variants = [
  {
    name: "HbProgressButtonActive",
    type: "variant",
  },
];

export default HbProgressButton;
