// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbProgress.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ContainerPrimitive } from "./_internal_primitives";
import HbProgressBarComposite, { HbProgressBarContext } from "./HbProgressBar";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      kmSY4sXvkg: {},
    },
  },
];

const variantPropTypes = [];

export const HbProgressContext = createContext(null);

function HbProgress(_props) {
  const defaults = useContext(HbProgressContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="MxbtnZbZYP"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "MxbtnZbZYP",
        scope: "58sVdZPWz3",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.HbProgressBar === undefined ? (
          <HbProgressBarComposite
            key={"kmSY4sXvkg"}
            {...getCompositeDefaultProps("kmSY4sXvkg")}
            className="__visly_reset __visly_scope_58sVdZPWz3_kmSY4sXvkg"
          />
        ) : (
          <HbProgressBarContext.Provider
            key="kmSY4sXvkg-provider"
            value={{
              key: "kmSY4sXvkg",
              className: "__visly_reset __visly_scope_58sVdZPWz3_kmSY4sXvkg",
              ...getCompositeDefaultProps("kmSY4sXvkg"),
            }}
          >
            {props.HbProgressBar}
          </HbProgressBarContext.Provider>
        ),
        <ContainerPrimitive
          className={"__visly_reset __visly_scope_58sVdZPWz3_9C7DRr8xaT"}
          key={"9C7DRr8xaT"}
          addSpacing={false}
        >
          {
            <ContainerPrimitive
              key={"WSVto4bCsC"}
              className={"__visly_reset __visly_scope_58sVdZPWz3_WSVto4bCsC"}
              addSpacing={false}
            >
              {props.children}
            </ContainerPrimitive>
          }
        </ContainerPrimitive>,
      ]}
    </RootPrimitive>
  );
}

HbProgress.HbProgressBar = HbProgressBarComposite;
HbProgress.__variants = [];

export default HbProgress;
