// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbSelect.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { TextPrimitive } from "./_internal_primitives";
import {
  SelectRoot,
  SelectOptionContainer,
  SelectButton,
} from "./_internal_select";

const styles = [
  {
    type: "default",
    layers: {
      "select-button-text": {
        none: {
          text: "Selected",
        },
      },
    },
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "small",
        layers: {},
      },
      {
        propValue: "medium",
        layers: {},
      },
      {
        propValue: "large",
        layers: {},
      },
      {
        propValue: "super",
        layers: {},
      },
    ],
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "enum",
    propName: "size",
    values: [
      {
        propValue: "small",
        layers: {},
      },
      {
        propValue: "medium",
        layers: {},
      },
      {
        propValue: "large",
        layers: {},
      },
      {
        propValue: "super",
        layers: {},
      },
    ],
  },
];

const variantPropTypes = [
  {
    type: "enum",
    propName: "size",
    propValues: ["small", "medium", "large", "super"],
  },
];

export const HbSelectContext = createContext(null);

function HbSelect(_props) {
  const defaults = useContext(HbSelectContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <SelectRoot
      {...props}
      key="select-root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "select-root",
        scope: "AaLudVhbjf",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <SelectButton
            key="select-button"
            className="__visly_reset __visly_scope_AaLudVhbjf_select-button"
          >
            {
              <TextPrimitive
                className={
                  "__visly_reset __visly_scope_AaLudVhbjf_select-button-text"
                }
                key={"select-button-text"}
                text={
                  exists(props.label)
                    ? props.label
                    : getStyle("select-button-text", "text")
                }
              />
            }
          </SelectButton>
          <SelectOptionContainer
            key="select-menu"
            className="__visly_reset __visly_scope_AaLudVhbjf_select-menu"
            innerKey="select-menu"
            addSpacing={false}
            useButtonWidth={true}
          >
            {props.children}
          </SelectOptionContainer>
        </>
      )}
    </SelectRoot>
  );
}

HbSelect.__variants = [
  {
    name: "size",
    type: "group",
    variants: ["small", "medium", "large", "super"],
  },
];

export default HbSelect;
