// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./HbTitle.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      tkWWpRpjf3: {
        none: {
          text: "Text",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbTitleContext = createContext(null);

function HbTitle(_props) {
  const defaults = useContext(HbTitleContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="L83WkqFJnB"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "L83WkqFJnB",
        scope: "FZkfHq6MCA",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <TextPrimitive
            className={"__visly_reset __visly_scope_FZkfHq6MCA_tkWWpRpjf3"}
            key={"tkWWpRpjf3"}
            text={getStyle("tkWWpRpjf3", "text")}
          />
          <ContainerPrimitive
            key={"DxEPUaudXV"}
            className={"__visly_reset __visly_scope_FZkfHq6MCA_DxEPUaudXV"}
            addSpacing={false}
          >
            {props.children}
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

HbTitle.__variants = [];

export default HbTitle;
