// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./MyButton.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  SpacerPrimitive,
  TextPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import { ButtonRoot } from "./_internal_button";

const styles = [
  {
    type: "default",
    layers: {
      Y4NZR89ePN: {
        none: {
          text: "Button",
        },
      },
      TRVJGP8dCW: {
        none: {
          role: "img",
          src: require("../assets/335f3298-73c2-4b49-87f0-bdd5380a4035@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const MyButtonContext = createContext(null);

function MyButton(_props) {
  const defaults = useContext(MyButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ButtonRoot
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "root",
        scope: "YVt6LBXS9Q",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <IconPrimitive
            className={"__visly_reset __visly_scope_YVt6LBXS9Q_TRVJGP8dCW"}
            key={"TRVJGP8dCW"}
            useMask={getStyle("TRVJGP8dCW", "useMask")}
            src={
              exists(props.icon) ? props.icon : getStyle("TRVJGP8dCW", "src")
            }
          />
          <SpacerPrimitive
            className={"__visly_reset __visly_scope_YVt6LBXS9Q_DMHHuu8ci7"}
            key={"DMHHuu8ci7"}
          />
          <TextPrimitive
            className={"__visly_reset __visly_scope_YVt6LBXS9Q_Y4NZR89ePN"}
            key={"Y4NZR89ePN"}
            text={
              exists(props.text) ? props.text : getStyle("Y4NZR89ePN", "text")
            }
          />
        </>
      )}
    </ButtonRoot>
  );
}

MyButton.__variants = [];

export default MyButton;
