// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./Radio.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const RadioContext = createContext(null);

function Radio(_props) {
  const defaults = useContext(RadioContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="XymjPmbr4f"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "XymjPmbr4f",
        scope: "Vr7F3w7Ssj",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => null}
    </RootPrimitive>
  );
}

Radio.__variants = [];

export default Radio;
