// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./ReshareButton.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  SpacerPrimitive,
  TextPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import { ToggleButtonRoot } from "./_internal_togglebutton";

const styles = [
  {
    type: "default",
    layers: {
      "336oAbe272": {
        none: {
          text: "102",
        },
      },
      YLowiHcxUk: {
        none: {
          role: "img",
          src: require("../assets/7900b30b-3148-4379-bb23-489f4b637df5@1x.svg"),
          useMask: true,
        },
        hover: {
          useMask: true,
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {
      YLowiHcxUk: {
        none: {
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "checked",
  },
];

export const ReshareButtonContext = createContext(null);

function ReshareButton(_props) {
  const defaults = useContext(ReshareButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ToggleButtonRoot
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "root",
        scope: "4tN4fh4RLM",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <IconPrimitive
            className={"__visly_reset __visly_scope_4tN4fh4RLM_YLowiHcxUk"}
            key={"YLowiHcxUk"}
            useMask={getStyle("YLowiHcxUk", "useMask")}
            src={
              exists(props.icon) ? props.icon : getStyle("YLowiHcxUk", "src")
            }
          />
          <SpacerPrimitive
            className={"__visly_reset __visly_scope_4tN4fh4RLM_QqpfPi4ifo"}
            key={"QqpfPi4ifo"}
          />
          <TextPrimitive
            className={"__visly_reset __visly_scope_4tN4fh4RLM_336oAbe272"}
            key={"336oAbe272"}
            text={
              exists(props.text) ? props.text : getStyle("336oAbe272", "text")
            }
          />
        </>
      )}
    </ToggleButtonRoot>
  );
}

ReshareButton.__variants = [
  {
    name: "checked",
    type: "variant",
  },
];

export default ReshareButton;
