// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./SocialPost.Image.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, ImagePrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const ImageContext = createContext(null);

function Image(_props) {
  const defaults = useContext(ImageContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="NfxRNjDcRr"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "NfxRNjDcRr",
        scope: "PaLZDRFNMV",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ImagePrimitive
          className={"__visly_reset __visly_scope_PaLZDRFNMV_EoT1a1rWD5"}
          key={"EoT1a1rWD5"}
          src={
            exists(props.imageSrc)
              ? props.imageSrc
              : getStyle("EoT1a1rWD5", "src")
          }
          alt={getStyle("EoT1a1rWD5", "alternateText")}
        />
      )}
    </RootPrimitive>
  );
}

Image.__variants = [];

export default Image;
