// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./SocialPost.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "./_internal_primitives";
import ReshareButtonComposite, { ReshareButtonContext } from "./ReshareButton";
import LikeButtonComposite, { LikeButtonContext } from "./LikeButton";
import CommentButtonComposite, { CommentButtonContext } from "./CommentButton";
import AvatarComposite, { AvatarContext } from "./Avatar";
import ShareButtonCompound from "./SocialPost.ShareButton";

const styles = [
  {
    type: "default",
    layers: {
      XkPq6xE9gW: {
        none: {
          text: "Visly",
        },
      },
      TvarQTGmjR: {
        none: {
          text: "@vislyhq",
        },
      },
      M26BMeU8Ea: {
        none: {
          text: "12h",
        },
      },
      CXtDUxARb4: {
        none: {
          text:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        },
      },
      YCHFBCViZ5: {
        none: {
          text: "•",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      FCGS5zXokx: {},
      F9TMVU8PAe: {},
      CwrChaTPaY: {},
      BKkQ7CrgDM: {},
    },
  },
];

const variantPropTypes = [];

export const SocialPostContext = createContext(null);

function SocialPost(_props) {
  const defaults = useContext(SocialPostContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="MRtAABMZV9"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "MRtAABMZV9",
        scope: "NA7dQZBwWp",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ContainerPrimitive
          className={"__visly_reset __visly_scope_NA7dQZBwWp_URQ4q9d8Vx"}
          key={"URQ4q9d8Vx"}
          addSpacing={false}
        >
          {[
            props.Avatar === undefined ? (
              <AvatarComposite
                key={"BKkQ7CrgDM"}
                {...getCompositeDefaultProps("BKkQ7CrgDM")}
                className="__visly_reset __visly_scope_NA7dQZBwWp_BKkQ7CrgDM"
              />
            ) : (
              <AvatarContext.Provider
                key="BKkQ7CrgDM-provider"
                value={{
                  key: "BKkQ7CrgDM",
                  className:
                    "__visly_reset __visly_scope_NA7dQZBwWp_BKkQ7CrgDM",
                  ...getCompositeDefaultProps("BKkQ7CrgDM"),
                }}
              >
                {props.Avatar}
              </AvatarContext.Provider>
            ),
            <SpacerPrimitive
              className={"__visly_reset __visly_scope_NA7dQZBwWp_S62eHGkSGV"}
              key={"S62eHGkSGV"}
            />,
            <ContainerPrimitive
              className={"__visly_reset __visly_scope_NA7dQZBwWp_JJ2QKdqd9K"}
              key={"JJ2QKdqd9K"}
              addSpacing={false}
            >
              <ContainerPrimitive
                className={"__visly_reset __visly_scope_NA7dQZBwWp_WNjVPzPTaf"}
                key={"WNjVPzPTaf"}
                addSpacing={true}
              >
                <TextPrimitive
                  className={
                    "__visly_reset __visly_scope_NA7dQZBwWp_XkPq6xE9gW"
                  }
                  key={"XkPq6xE9gW"}
                  text={
                    exists(props.name)
                      ? props.name
                      : getStyle("XkPq6xE9gW", "text")
                  }
                />
                <TextPrimitive
                  className={
                    "__visly_reset __visly_scope_NA7dQZBwWp_TvarQTGmjR"
                  }
                  key={"TvarQTGmjR"}
                  text={
                    exists(props.handle)
                      ? props.handle
                      : getStyle("TvarQTGmjR", "text")
                  }
                />
                <TextPrimitive
                  className={
                    "__visly_reset __visly_scope_NA7dQZBwWp_YCHFBCViZ5"
                  }
                  key={"YCHFBCViZ5"}
                  text={getStyle("YCHFBCViZ5", "text")}
                />
                <TextPrimitive
                  className={
                    "__visly_reset __visly_scope_NA7dQZBwWp_M26BMeU8Ea"
                  }
                  key={"M26BMeU8Ea"}
                  text={
                    exists(props.date)
                      ? props.date
                      : getStyle("M26BMeU8Ea", "text")
                  }
                />
              </ContainerPrimitive>
              <SpacerPrimitive
                className={"__visly_reset __visly_scope_NA7dQZBwWp_JzzhiuaAFq"}
                key={"JzzhiuaAFq"}
              />
              <TextPrimitive
                className={"__visly_reset __visly_scope_NA7dQZBwWp_CXtDUxARb4"}
                key={"CXtDUxARb4"}
                text={
                  exists(props.text)
                    ? props.text
                    : getStyle("CXtDUxARb4", "text")
                }
              />
              <SpacerPrimitive
                className={"__visly_reset __visly_scope_NA7dQZBwWp_2zzcNNNh2G"}
                key={"2zzcNNNh2G"}
              />
              <ContainerPrimitive
                key={"6sciBBY5sU"}
                className={"__visly_reset __visly_scope_NA7dQZBwWp_6sciBBY5sU"}
                addSpacing={false}
              >
                {props.attachment}
              </ContainerPrimitive>
              <SpacerPrimitive
                className={"__visly_reset __visly_scope_NA7dQZBwWp_6ymo9M6kkD"}
                key={"6ymo9M6kkD"}
              />
              <ContainerPrimitive
                className={"__visly_reset __visly_scope_NA7dQZBwWp_U1kjCAJn9J"}
                key={"U1kjCAJn9J"}
                addSpacing={true}
              >
                {[
                  props.CommentButton === undefined ? (
                    <CommentButtonComposite
                      key={"CwrChaTPaY"}
                      {...getCompositeDefaultProps("CwrChaTPaY")}
                      className="__visly_reset __visly_scope_NA7dQZBwWp_CwrChaTPaY"
                    />
                  ) : (
                    <CommentButtonContext.Provider
                      key="CwrChaTPaY-provider"
                      value={{
                        key: "CwrChaTPaY",
                        className:
                          "__visly_reset __visly_scope_NA7dQZBwWp_CwrChaTPaY",
                        ...getCompositeDefaultProps("CwrChaTPaY"),
                      }}
                    >
                      {props.CommentButton}
                    </CommentButtonContext.Provider>
                  ),
                  props.ReshareButton === undefined ? (
                    <ReshareButtonComposite
                      key={"FCGS5zXokx"}
                      {...getCompositeDefaultProps("FCGS5zXokx")}
                      className="__visly_reset __visly_scope_NA7dQZBwWp_FCGS5zXokx"
                    />
                  ) : (
                    <ReshareButtonContext.Provider
                      key="FCGS5zXokx-provider"
                      value={{
                        key: "FCGS5zXokx",
                        className:
                          "__visly_reset __visly_scope_NA7dQZBwWp_FCGS5zXokx",
                        ...getCompositeDefaultProps("FCGS5zXokx"),
                      }}
                    >
                      {props.ReshareButton}
                    </ReshareButtonContext.Provider>
                  ),
                  props.LikeButton === undefined ? (
                    <LikeButtonComposite
                      key={"F9TMVU8PAe"}
                      {...getCompositeDefaultProps("F9TMVU8PAe")}
                      className="__visly_reset __visly_scope_NA7dQZBwWp_F9TMVU8PAe"
                    />
                  ) : (
                    <LikeButtonContext.Provider
                      key="F9TMVU8PAe-provider"
                      value={{
                        key: "F9TMVU8PAe",
                        className:
                          "__visly_reset __visly_scope_NA7dQZBwWp_F9TMVU8PAe",
                        ...getCompositeDefaultProps("F9TMVU8PAe"),
                      }}
                    >
                      {props.LikeButton}
                    </LikeButtonContext.Provider>
                  ),
                  props.ShareButton === undefined ? (
                    <ShareButtonCompound key={"JWiy4kpCML"} />
                  ) : (
                    props.ShareButton
                  ),
                ]}
              </ContainerPrimitive>
            </ContainerPrimitive>,
          ]}
        </ContainerPrimitive>
      )}
    </RootPrimitive>
  );
}

SocialPost.ReshareButton = ReshareButtonComposite;
SocialPost.LikeButton = LikeButtonComposite;
SocialPost.CommentButton = CommentButtonComposite;
SocialPost.Avatar = AvatarComposite;
SocialPost.__variants = [];

export default SocialPost;
