// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./TeStO.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive } from "./_internal_primitives";
import HbIconButtonComposite, { HbIconButtonContext } from "./HbIconButton";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      H4cHZs5ogG: {
        none: {
          HbIconButtonSelected: true,
          size: "small",
        },
      },
    },
  },
];

const variantPropTypes = [];

export const TeStOContext = createContext(null);

function TeStO(_props) {
  const defaults = useContext(TeStOContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="5gkt6FohPd"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "5gkt6FohPd",
        scope: "WgWgtvBdrX",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) =>
        props.HbIconButton === undefined ? (
          <HbIconButtonComposite
            key={"H4cHZs5ogG"}
            {...getCompositeDefaultProps("H4cHZs5ogG")}
            className="__visly_reset __visly_scope_WgWgtvBdrX_H4cHZs5ogG"
          />
        ) : (
          <HbIconButtonContext.Provider
            key="H4cHZs5ogG-provider"
            value={{
              key: "H4cHZs5ogG",
              className: "__visly_reset __visly_scope_WgWgtvBdrX_H4cHZs5ogG",
              ...getCompositeDefaultProps("H4cHZs5ogG"),
            }}
          >
            {props.HbIconButton}
          </HbIconButtonContext.Provider>
        )
      }
    </RootPrimitive>
  );
}

TeStO.HbIconButton = HbIconButtonComposite;
TeStO.__variants = [];

export default TeStO;
