// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./HbFeatureInvert.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  ContainerPrimitive,
} from "../_internal_primitives";
import HbFeatureItemComposite, {
  HbFeatureItemContext,
} from "../Compounds/HbFeatureItem";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      RWAtM6Cbek: {},
    },
  },
];

const variantPropTypes = [];

export const HbFeatureInvertContext = createContext(null);

function HbFeatureInvert(_props) {
  const defaults = useContext(HbFeatureInvertContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="QF3aX47C17"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "QF3aX47C17",
        scope: "SPtN2tvqGr",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        props.HbFeatureItem === undefined ? (
          <HbFeatureItemComposite
            key={"RWAtM6Cbek"}
            {...getCompositeDefaultProps("RWAtM6Cbek")}
            className="__visly_reset __visly_scope_SPtN2tvqGr_RWAtM6Cbek"
          />
        ) : (
          <HbFeatureItemContext.Provider
            key="RWAtM6Cbek-provider"
            value={{
              key: "RWAtM6Cbek",
              className: "__visly_reset __visly_scope_SPtN2tvqGr_RWAtM6Cbek",
              ...getCompositeDefaultProps("RWAtM6Cbek"),
            }}
          >
            {props.HbFeatureItem}
          </HbFeatureItemContext.Provider>
        ),
        <SpacerPrimitive
          className={"__visly_reset __visly_scope_SPtN2tvqGr_AniiyGaDfa"}
          key={"AniiyGaDfa"}
        />,
        <ContainerPrimitive
          className={"__visly_reset __visly_scope_SPtN2tvqGr_KxhjEmTBpq"}
          key={"KxhjEmTBpq"}
          addSpacing={false}
          element={getStyle("KxhjEmTBpq", "htmlElement")}
        >
          {
            <ImagePrimitive
              className={"__visly_reset __visly_scope_SPtN2tvqGr_NtUhg3o63o"}
              key={"NtUhg3o63o"}
              src={
                exists(props.imageSrc)
                  ? props.imageSrc
                  : getStyle("NtUhg3o63o", "src")
              }
              alt={getStyle("NtUhg3o63o", "alternateText")}
            />
          }
        </ContainerPrimitive>,
        <SpacerPrimitive
          className={"__visly_reset __visly_scope_SPtN2tvqGr_2VS5uK6ip5"}
          key={"2VS5uK6ip5"}
        />,
      ]}
    </RootPrimitive>
  );
}

HbFeatureInvert.HbFeatureItem = HbFeatureItemComposite;
HbFeatureInvert.__variants = [];

export default HbFeatureInvert;
