// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./HbProductEmpty.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
} from "../_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      "72EEoP6Shu": {
        none: {
          text:
            "Unfortunately we don’t have a Hungry Bark Supplement to offer him. Want to discuss this further?  Contact us",
        },
      },
      "21QeGg8jho": {
        none: {
          text: "1",
        },
      },
      HM7QLqsybb: {
        none: {
          text: "Type",
        },
      },
      WhwzT2jENf: {
        none: {
          role: "img",
          src: require("../assets/b5e18a86-70b3-4310-9998-74fd8910ec42.svg"),
          useMask: true,
        },
      },
      "8C3DGxh663": {
        none: {
          text: "Oops… Looks like Oscar has some very specific needs…",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbProductEmptyContext = createContext(null);

function HbProductEmpty(_props) {
  const defaults = useContext(HbProductEmptyContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="TEMvSpZsq9"
      addSpacing={true}
      internal={{
        styles: styles,
        layerId: "TEMvSpZsq9",
        scope: "GVHshrcqto",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_GVHshrcqto_DA8Xa72aFn"}
            key={"DA8Xa72aFn"}
            addSpacing={true}
          >
            {
              <ContainerPrimitive
                className={"__visly_reset __visly_scope_GVHshrcqto_WRyAaE5y9d"}
                key={"WRyAaE5y9d"}
                addSpacing={true}
              >
                <ContainerPrimitive
                  className={
                    "__visly_reset __visly_scope_GVHshrcqto_Um5F7YdKHX"
                  }
                  key={"Um5F7YdKHX"}
                  addSpacing={false}
                >
                  {
                    <TextPrimitive
                      className={
                        "__visly_reset __visly_scope_GVHshrcqto_21QeGg8jho"
                      }
                      key={"21QeGg8jho"}
                      text={
                        exists(props.order)
                          ? props.order
                          : getStyle("21QeGg8jho", "text")
                      }
                    />
                  }
                </ContainerPrimitive>
                <TextPrimitive
                  className={
                    "__visly_reset __visly_scope_GVHshrcqto_HM7QLqsybb"
                  }
                  key={"HM7QLqsybb"}
                  text={
                    exists(props.type)
                      ? props.type
                      : getStyle("HM7QLqsybb", "text")
                  }
                />
              </ContainerPrimitive>
            }
          </ContainerPrimitive>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_GVHshrcqto_UdYVCcCaqY"}
            key={"UdYVCcCaqY"}
            addSpacing={false}
          >
            <ContainerPrimitive
              className={"__visly_reset __visly_scope_GVHshrcqto_CTQf35YXup"}
              key={"CTQf35YXup"}
              addSpacing={false}
            >
              {
                <IconPrimitive
                  className={
                    "__visly_reset __visly_scope_GVHshrcqto_WhwzT2jENf"
                  }
                  key={"WhwzT2jENf"}
                  useMask={getStyle("WhwzT2jENf", "useMask")}
                  src={getStyle("WhwzT2jENf", "src")}
                />
              }
            </ContainerPrimitive>
            <SpacerPrimitive
              className={"__visly_reset __visly_scope_GVHshrcqto_JLos9DaYE8"}
              key={"JLos9DaYE8"}
            />
            <ContainerPrimitive
              className={"__visly_reset __visly_scope_GVHshrcqto_N3yQYTcaWV"}
              key={"N3yQYTcaWV"}
              addSpacing={false}
            >
              <TextPrimitive
                className={"__visly_reset __visly_scope_GVHshrcqto_8C3DGxh663"}
                key={"8C3DGxh663"}
                text={
                  exists(props.oops)
                    ? props.oops
                    : getStyle("8C3DGxh663", "text")
                }
              />
              <SpacerPrimitive
                className={"__visly_reset __visly_scope_GVHshrcqto_X6tktLxhFT"}
                key={"X6tktLxhFT"}
              />
              <TextPrimitive
                className={"__visly_reset __visly_scope_GVHshrcqto_72EEoP6Shu"}
                key={"72EEoP6Shu"}
                text={
                  exists(props.textAndLink)
                    ? props.textAndLink
                    : getStyle("72EEoP6Shu", "text")
                }
              />
              <ContainerPrimitive
                key={"KVQd13HGDM"}
                className={"__visly_reset __visly_scope_GVHshrcqto_KVQd13HGDM"}
                addSpacing={false}
              >
                {props.details}
              </ContainerPrimitive>
            </ContainerPrimitive>
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

HbProductEmpty.__variants = [];

export default HbProductEmpty;
