// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./HbStickyBar.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      K8Rvc3Sc8R: {
        none: {
          htmlElement: "footer",
        },
      },
      Cv9QgvrcGc: {
        none: {
          text: "Text",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbStickyBarContext = createContext(null);

function HbStickyBar(_props) {
  const defaults = useContext(HbStickyBarContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="k3jaASDPhw"
      addSpacing={false}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "k3jaASDPhw",
        scope: "3Fk3gvCxrB",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <ContainerPrimitive
          id={"Container_K8Rvc3Sc8R"}
          className={
            "__visly_reset_WDRq65T88Q __visly_scope_3Fk3gvCxrB_K8Rvc3Sc8R"
          }
          key={"K8Rvc3Sc8R"}
          addSpacing={false}
          element={getStyle("K8Rvc3Sc8R", "htmlElement")}
        >
          {
            <TextPrimitive
              id={"Text_Cv9QgvrcGc"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_3Fk3gvCxrB_Cv9QgvrcGc"
              }
              key={"Cv9QgvrcGc"}
              text={
                exists(props.text) ? props.text : getStyle("Cv9QgvrcGc", "text")
              }
              element={getStyle("Cv9QgvrcGc", "htmlElement")}
            />
          }
        </ContainerPrimitive>
      )}
    </RootPrimitive>
  );
}

HbStickyBar.__variants = [];

export default HbStickyBar;
