// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./HbTestimonial.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
} from "../_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      LLAN2HR72H: {
        none: {
          text: "So far so good!",
        },
      },
      "72EEoP6Shu": {
        none: {
          text:
            "Sed ut perspiciatis unde omnis iste natus error sit voluptat accusant doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        },
      },
      GfQQK2QSw7: {
        none: {
          text: "Mary Wilkerson",
        },
      },
      Jp3AYaDT1R: {
        none: {
          role: "img",
          src: require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const HbTestimonialContext = createContext(null);

function HbTestimonial(_props) {
  const defaults = useContext(HbTestimonialContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="TEMvSpZsq9"
      addSpacing={true}
      internal={{
        styles: styles,
        layerId: "TEMvSpZsq9",
        scope: "WBdVWKo3g2",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            key={"JcvuhRskdz"}
            className={"__visly_reset __visly_scope_WBdVWKo3g2_JcvuhRskdz"}
            addSpacing={false}
          >
            {props.stars}
          </ContainerPrimitive>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_WBdVWKo3g2_KoxVNRDdjs"}
            key={"KoxVNRDdjs"}
            addSpacing={false}
          >
            <TextPrimitive
              className={"__visly_reset __visly_scope_WBdVWKo3g2_GfQQK2QSw7"}
              key={"GfQQK2QSw7"}
              text={
                exists(props.client)
                  ? props.client
                  : getStyle("GfQQK2QSw7", "text")
              }
            />
            <SpacerPrimitive
              className={"__visly_reset __visly_scope_WBdVWKo3g2_KdmQLnbq1R"}
              key={"KdmQLnbq1R"}
            />
            <ContainerPrimitive
              className={"__visly_reset __visly_scope_WBdVWKo3g2_BPYvu5nk1j"}
              key={"BPYvu5nk1j"}
              addSpacing={false}
            >
              {
                <IconPrimitive
                  className={
                    "__visly_reset __visly_scope_WBdVWKo3g2_Jp3AYaDT1R"
                  }
                  key={"Jp3AYaDT1R"}
                  useMask={getStyle("Jp3AYaDT1R", "useMask")}
                  src={getStyle("Jp3AYaDT1R", "src")}
                />
              }
            </ContainerPrimitive>
          </ContainerPrimitive>
          <SpacerPrimitive
            className={"__visly_reset __visly_scope_WBdVWKo3g2_F1fTPjzhrX"}
            key={"F1fTPjzhrX"}
          />
          <TextPrimitive
            className={"__visly_reset __visly_scope_WBdVWKo3g2_LLAN2HR72H"}
            key={"LLAN2HR72H"}
            text={
              exists(props.title) ? props.title : getStyle("LLAN2HR72H", "text")
            }
          />
          <TextPrimitive
            className={"__visly_reset __visly_scope_WBdVWKo3g2_72EEoP6Shu"}
            key={"72EEoP6Shu"}
            text={
              exists(props.text) ? props.text : getStyle("72EEoP6Shu", "text")
            }
          />
        </>
      )}
    </RootPrimitive>
  );
}

HbTestimonial.__variants = [];

export default HbTestimonial;
