// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const heart: string;
export const heartFill: string;
export const message: string;
export const repeat: string;
export const share: string;
export const vislyCheck: string;
export const vislyRadioBorder: string;
export const vislyRadioCenter: string;
export const vislySelect: string;
