// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const hbDiscount = require("../assets/6c09c43b-abd0-4776-8845-1535cdff712b.svg");
export const hbFooterCustomNutrition = require("../assets/3421457c-3753-4949-b709-b4d47224a029.svg");
export const hbFooterPremium = require("../assets/886449e4-75e9-407f-b77d-2de8cc4a0895.svg");
export const hbFooterVetApproved = require("../assets/dbe16c81-bff3-4c34-a2cf-276c5ce67996.png");
export const hbLogo = require("../assets/a5992a54-5d1a-4992-af21-8bf2fbbf0184.svg");
export const hbLogoMobile = require("../assets/b903d3b8-3830-4199-b34c-ca76aadb867b.svg");
export const heart = require("../assets/335f3298-73c2-4b49-87f0-bdd5380a4035@1x.svg");
export const heartFill = require("../assets/fd204fbe-52a7-4ca8-becd-8a04ae285d64@1x.svg");
export const message = require("../assets/c960c1cc-f05b-4842-972b-c497154e2e5b@1x.svg");
export const svgBgLarge = require("../assets/c34da6fb-17bb-449d-ae53-54bf1f9947a3.svg");
export const svgBgMid = require("../assets/052769b9-0e55-45a8-b18e-fb64720aee75.svg");
export const svgBgSmall = require("../assets/ad421314-cf15-4362-b50c-70538a46066f.svg");
export const vislyCheck = require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg");
export const vislyRadioBorder = require("../assets/d0171f72-9dbe-4e54-b469-a4432d2beca6@1x.svg");
export const vislyRadioCenter = require("../assets/22ef53ca-3265-49f9-85f5-c00ff038c977@1x.svg");
export const vislySelect = require("../assets/c6f11592-eb2a-4697-9b7c-6c7c31b99f89@1x.svg");
