// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const hbActivityActive: string;
export const hbActivityAthlete: string;
export const hbActivityLazy: string;
export const hbChevronDown: string;
export const hbClose: string;
export const hbDiscount: string;
export const hbFemale: string;
export const hbFooterCustomNutrition: string;
export const hbFooterPremium: string;
export const hbFooterVetApproved: string;
export const hbLikesBeef: string;
export const hbLikesChicken: string;
export const hbLikesDuck: string;
export const hbLikesLamb: string;
export const hbLikesSalmon: string;
export const hbLikesTurkey: string;
export const hbLogo: string;
export const hbLogoMobile: string;
export const hbMale: string;
export const hbWeightIdeal: string;
export const hbWeightObese: string;
export const hbWeightThin: string;
export const heart: string;
export const heartFill: string;
export const message: string;
export const svgBgLarge: string;
export const svgBgMid: string;
export const svgBgSmall: string;
export const vislyCheck: string;
export const vislyRadioBorder: string;
export const vislyRadioCenter: string;
export const vislySelect: string;
