// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const hbDiscount: string;
export const hbFooterCustomNutrition: string;
export const hbFooterPremium: string;
export const hbFooterVetApproved: string;
export const hbLogo: string;
export const hbLogoMobile: string;
export const heart: string;
export const heartFill: string;
export const message: string;
export const svgBgLarge: string;
export const svgBgMid: string;
export const svgBgSmall: string;
export const vislyCheck: string;
export const vislyRadioBorder: string;
export const vislyRadioCenter: string;
export const vislySelect: string;
