// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const hbActivityActive = require("../assets/ccea071c-ea6f-420c-ae77-97c980ca65df.svg");
export const hbActivityAthlete = require("../assets/e7ceb85d-3a5e-4f0b-874e-894db4786a77.svg");
export const hbActivityLazy = require("../assets/c95ce908-5e59-45ba-b14f-882f777ab5b4.svg");
export const hbChevronDown = require("../assets/43a5e139-2110-4a5e-aacf-5845cb331df8.svg");
export const hbDiscount = require("../assets/6c09c43b-abd0-4776-8845-1535cdff712b.svg");
export const hbFemale = require("../assets/846d74d9-d068-4e7e-89bd-1fd401ba1b0a.png");
export const hbFooterCustomNutrition = require("../assets/3421457c-3753-4949-b709-b4d47224a029.svg");
export const hbFooterPremium = require("../assets/886449e4-75e9-407f-b77d-2de8cc4a0895.svg");
export const hbFooterVetApproved = require("../assets/dbe16c81-bff3-4c34-a2cf-276c5ce67996.png");
export const hbLikesBeef = require("../assets/193cfcfc-7a70-45db-a8fc-75c490a41a95.svg");
export const hbLikesChicken = require("../assets/2421b363-25ec-4a6d-b0bd-1a8c10f6d859.png");
export const hbLikesDuck = require("../assets/b59d95b4-286f-4093-9f30-45c7be15250d.svg");
export const hbLikesLamb = require("../assets/d7b43385-4f82-402b-82b5-5af719455f8f.svg");
export const hbLikesSalmon = require("../assets/bc8e5a7d-dadf-4110-bae8-08995f863e8d.svg");
export const hbLikesTurkey = require("../assets/cd1f3003-d65a-4408-8b07-601054571bc6.svg");
export const hbLogo = require("../assets/17a82962-2adc-4a57-a7ef-b52a36220673.svg");
export const hbLogoMobile = require("../assets/b903d3b8-3830-4199-b34c-ca76aadb867b.svg");
export const hbMale = require("../assets/6ed7698a-cec1-4d22-b634-8cf9b5fc6a50.png");
export const hbWeightIdeal = require("../assets/55a83afb-fea1-40f5-9ddc-a4f743e2c415.svg");
export const hbWeightObese = require("../assets/89335584-74ed-4b60-8c4f-60c67c96910c.svg");
export const hbWeightThin = require("../assets/d9f86f16-39ab-4609-8e42-5e4e0f204d90.svg");
export const heart = require("../assets/335f3298-73c2-4b49-87f0-bdd5380a4035@1x.svg");
export const heartFill = require("../assets/fd204fbe-52a7-4ca8-becd-8a04ae285d64@1x.svg");
export const message = require("../assets/c960c1cc-f05b-4842-972b-c497154e2e5b@1x.svg");
export const svgBgLarge = require("../assets/c34da6fb-17bb-449d-ae53-54bf1f9947a3.svg");
export const svgBgMid = require("../assets/052769b9-0e55-45a8-b18e-fb64720aee75.svg");
export const svgBgSmall = require("../assets/ad421314-cf15-4362-b50c-70538a46066f.svg");
export const vislyCheck = require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg");
export const vislyRadioBorder = require("../assets/d0171f72-9dbe-4e54-b469-a4432d2beca6@1x.svg");
export const vislyRadioCenter = require("../assets/22ef53ca-3265-49f9-85f5-c00ff038c977@1x.svg");
export const vislySelect = require("../assets/c6f11592-eb2a-4697-9b7c-6c7c31b99f89@1x.svg");
