// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const color: {
  black700: "65f847a3-aa95-4f42-9cdf-cd8dbe73d8c2";
  black800: "1ecb2015-0125-4ee5-9d8c-feb10369dac8";
  black900: "0b266fa6-2ad0-4f8a-90ff-56ca470c31c7";
  gray200: "544af3b8-8dfd-4496-ae15-220dc87c055f";
  gray300: "b6b28ca8-f2fd-4289-b56e-d98eefcbfcf9";
  gray400: "3aef1344-5ee8-443f-9160-554f2bba1159";
  gray500: "c4166644-3768-4c22-a10b-e1c9b6d61b96";
  mint400: "2e800351-2272-4773-a849-66d9cc1dbba7";
  mint500: "32f153bc-91ca-4170-9823-f1d2cd61ce38";
  mint600: "3d698970-2b19-4497-bc20-da4de161a26f";
  purple200: "c4cc314d-1c27-4d94-a2e3-694f87f9940e";
  purple400: "efb8d429-1324-49bd-aade-fed9012c47bc";
  purple500: "7ce0b38c-2947-49fa-a348-06bd21664357";
  purple600: "e8face8d-a42e-40ac-83e2-9bb4a97ecb4d";
  red400: "d1b0cc7c-00fc-4113-a9db-3d90f2dc54bb";
  white: "1a46fecf-73b1-44d3-88f8-69ef863d110a";
};
export const icon: {
  heart: "873969b2-f5fd-49f3-96aa-45f9515bff85";
  heartFill: "72d60e6c-6c0f-47f3-ba45-a6a42cf6250e";
  message: "c960c1cc-f05b-4842-972b-c497154e2e5b";
  repeat: "7900b30b-3148-4379-bb23-489f4b637df5";
  share: "c0d36d31-1367-4c7a-91be-c1ac14e5c3c5";
  vislyCheck: "567b267e-ef5e-4078-b042-d5c96e513048";
  vislyRadioBorder: "d0171f72-9dbe-4e54-b469-a4432d2beca6";
  vislyRadioCenter: "22ef53ca-3265-49f9-85f5-c00ff038c977";
  vislySelect: "562e1b22-bb85-483b-b4a0-52c23363fef5";
};
export const font: {
  "Roboto-Bold": "d7d2c5b4-4c7b-4efb-9c21-0ef70f800be8";
  "Roboto-Medium": "925b1f14-e32f-4af1-b2ee-80132fd73b20";
  "Roboto-Regular": "c775fc02-e85e-4e5f-b67a-b62e4ed19fb9";
  "Inter-Black": "2db51490-ce4e-4db8-9f10-4d0b24a059de";
  "Inter-BlackItalic": "82812a09-0fa5-4251-bc27-e9b0af32b813";
  "Inter-ExtraBold": "0c9a5879-0e21-4227-b2bc-99d300e43e52";
  "Inter-Bold": "7a7256d5-465e-4420-a713-c96bce455d8c";
  "Inter-BoldItalic": "652b3044-fc52-4daf-8ed6-c23f6b0696e2";
  "Inter-ExtraBoldItalic": "12e1b958-3c86-4f4b-b1ad-7ac1b470f79c";
  "Inter-ExtraLightItalic": "2348ce05-0aeb-44d2-8088-470a369c3121";
  "Inter-ExtraLight": "15503404-0609-41aa-b496-1b37912fe091";
  "Inter-Light": "fc164fb1-451b-44f0-a41b-f73111ffa6c4";
  "Inter-Italic": "d17dabe0-5132-4fb3-beae-0d01d1759f7a";
  "Inter-LightItalic": "bde81d66-a8fe-4215-be53-f48510d21785";
  "Inter-Medium": "a0752896-a456-40db-82df-44418f8af538";
  "Inter-Regular": "b0c0f064-81be-4383-993f-74528150ee81";
  "Inter-SemiBold": "fe6f3a02-ee87-443a-ace7-167a9af185cd";
  "Inter-MediumItalic": "ac425dad-6034-476b-973f-b77153d3f0a8";
  "Inter-SemiBoldItalic": "47fa28fd-8c21-4716-b4ff-5338824b33ef";
  "Inter-ThinItalic": "485e0fcf-ba64-4390-b6d0-92057cc52529";
  "Inter-Thin": "f8cd0728-b297-4161-94c2-5ba185d1e09a";
};
export const textstyle: {
  accent: "5a5b282c-fbe5-4efb-8163-9d8e2399991c";
  body: "199b4f45-79d7-45f8-af30-5d9a0d539bcc";
  bodyLarge: "f44a4b6d-a6ec-4bbd-a6b5-46a55cba7085";
  heading: "356b1e56-5565-4a97-bb9f-d812d1c7c56e";
};
export const size: {};
export const shadow: {};
export const component: {
  Avatar: "14c1309e-04d6-4426-b5bf-741031ceb68a";
  Button: "215624d8-a3e1-4139-928a-11eae36fd386";
  Checkbox: "12f2f79a-efe1-44b5-a6ea-94ebaac3ce59";
  CommentButton: "e8422644-7679-4a4b-a65e-50063492d6f1";
  Input: "50e2110b-155c-4778-a63c-44c9c1c8b4f1";
  LikeButton: "132f9c60-5ba4-4590-8aeb-1e98bbc83328";
  MyButton: "ff139c4b-836a-413a-adba-d295ba0845af";
  Radio: "e99b2c94-0602-42df-b146-28e8b7e747ca";
  ReshareButton: "1f775434-5b55-49f3-8ea9-9fcee4c6f463";
  Segmented: "b1be7efc-2508-4c36-92d1-ddbb567eba4c";
  Select: "45b37cde-13b4-4c47-ad5e-7ce42f64a2b8";
  SocialPost: "02f43c6d-09cb-4b9d-ab56-184f635e9ee3";
  Toggle: "c59ec177-5731-4a8e-8de4-f351d0c52542";
};
