// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const black700: string;
export const black800: string;
export const black900: string;
export const gray200: string;
export const gray300: string;
export const gray400: string;
export const gray500: string;
export const hbBrown: string;
export const hbGold: string;
export const hbGray300: string;
export const hbGreen: string;
export const hbText: string;
export const mint400: string;
export const mint500: string;
export const mint600: string;
export const purple200: string;
export const purple400: string;
export const purple500: string;
export const purple600: string;
export const red400: string;
export const white: string;
