// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const black700 = "rgba(74,76,82,1)";
export const black800 = "rgba(36,37,38,1)";
export const black900 = "rgba(16,16,16,1)";
export const gray200 = "rgba(237,239,242,1)";
export const gray300 = "rgba(217,218,230,1)";
export const gray400 = "rgba(170,174,181,1)";
export const gray500 = "rgba(129,134,140,1)";
export const hbGreen = "rgba(0,174,170,1)";
export const hbText = "rgba(36,36,36,1)";
export const mint400 = "rgba(0,193,159,1)";
export const mint500 = "rgba(0,137,123,1)";
export const mint600 = "rgba(0,99,91,1)";
export const purple200 = "rgba(199,177,230,1)";
export const purple400 = "rgba(144,99,205,1)";
export const purple500 = "rgba(117,59,189,1)";
export const purple600 = "rgba(81,33,121,1)";
export const red400 = "rgba(231,60,62,1)";
export const white = "rgba(255,255,255,1)";
