// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "../reset.css";
import "./HbLoadingScreen.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
} from "../_internal_primitives";
import HbProgressBarComposite, { HbProgressBarContext } from "../HbProgressBar";
import HbFirstSlideFooterComposite, {
  HbFirstSlideFooterContext,
} from "../HbFirstSlideFooter";

const styles = [
  {
    type: "default",
    layers: {
      TF559DqWXE: {
        none: {
          icon: require("../assets/17a82962-2adc-4a57-a7ef-b52a36220673.svg"),
          useMask: true,
        },
      },
      WCSj3htCLu: {
        none: {
          text: "Text",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      GHuiAcBnVY: {
        none: {
          golden: true,
        },
      },
      VkW5vGa1r6: {},
    },
  },
];

const variantPropTypes = [];

export const HbLoadingScreenContext = createContext(null);

function HbLoadingScreen(_props) {
  const defaults = useContext(HbLoadingScreenContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="WfC8wEAYmR"
      addSpacing={false}
      internal={{
        projectId: "WDRq65T88Q",
        styles: styles,
        layerId: "WfC8wEAYmR",
        scope: "2Zvr78cate",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            id={"Header_6MBJoo4gou"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_6MBJoo4gou"
            }
            key={"6MBJoo4gou"}
            addSpacing={false}
            element={getStyle("6MBJoo4gou", "htmlElement")}
          >
            {[
              <ContainerPrimitive
                id={"Head_Lw4AuqLvRj"}
                className={
                  "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_Lw4AuqLvRj"
                }
                key={"Lw4AuqLvRj"}
                addSpacing={false}
                element={getStyle("Lw4AuqLvRj", "htmlElement")}
              >
                {
                  <ContainerPrimitive
                    id={"Logo_9NuKFcPxSx"}
                    className={
                      "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_9NuKFcPxSx"
                    }
                    key={"9NuKFcPxSx"}
                    addSpacing={false}
                    element={getStyle("9NuKFcPxSx", "htmlElement")}
                  >
                    {
                      <IconPrimitive
                        id={"Icon_TF559DqWXE"}
                        className={
                          "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_TF559DqWXE"
                        }
                        key={"TF559DqWXE"}
                        useMask={getStyle("TF559DqWXE", "useMask")}
                        src={getStyle("TF559DqWXE", "icon")}
                      />
                    }
                  </ContainerPrimitive>
                }
              </ContainerPrimitive>,
              props.HbProgressBar === undefined ? (
                <HbProgressBarComposite
                  key={"GHuiAcBnVY"}
                  {...getCompositeDefaultProps("GHuiAcBnVY")}
                  id="HbProgressBar_GHuiAcBnVY"
                  className="__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_GHuiAcBnVY"
                />
              ) : (
                <HbProgressBarContext.Provider
                  key="GHuiAcBnVY-provider"
                  value={{
                    key: "GHuiAcBnVY",
                    id: "HbProgressBar_GHuiAcBnVY",
                    className:
                      "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_GHuiAcBnVY",
                    ...getCompositeDefaultProps("GHuiAcBnVY"),
                  }}
                >
                  {props.HbProgressBar}
                </HbProgressBarContext.Provider>
              ),
            ]}
          </ContainerPrimitive>
          <ContainerPrimitive
            id={"Content_5QBpZXrySw"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_5QBpZXrySw"
            }
            key={"5QBpZXrySw"}
            addSpacing={false}
            element={getStyle("5QBpZXrySw", "htmlElement")}
          >
            <ContainerPrimitive
              id={"Column_DJZPmZaYwR"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_DJZPmZaYwR"
              }
              key={"DJZPmZaYwR"}
              addSpacing={false}
              element={getStyle("DJZPmZaYwR", "htmlElement")}
            >
              {
                <ImagePrimitive
                  id={"Image_55PHVUTJ8V"}
                  className={
                    "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_55PHVUTJ8V"
                  }
                  key={"55PHVUTJ8V"}
                  src={
                    exists(props.imageSrc)
                      ? props.imageSrc
                      : getStyle("55PHVUTJ8V", "src")
                  }
                  alt={getStyle("55PHVUTJ8V", "alternateText")}
                />
              }
            </ContainerPrimitive>
            <SpacerPrimitive
              id={"Spacer_AYZWHdsAr6"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_AYZWHdsAr6"
              }
              key={"AYZWHdsAr6"}
            />
            <TextPrimitive
              id={"Text_WCSj3htCLu"}
              className={
                "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_WCSj3htCLu"
              }
              key={"WCSj3htCLu"}
              text={
                exists(props.text) ? props.text : getStyle("WCSj3htCLu", "text")
              }
              element={getStyle("WCSj3htCLu", "htmlElement")}
            />
          </ContainerPrimitive>
          <ContainerPrimitive
            id={"Footer_PWRTy8cZVP"}
            className={
              "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_PWRTy8cZVP"
            }
            key={"PWRTy8cZVP"}
            addSpacing={false}
            element={getStyle("PWRTy8cZVP", "htmlElement")}
          >
            {props.HbFirstSlideFooter === undefined ? (
              <HbFirstSlideFooterComposite
                key={"VkW5vGa1r6"}
                {...getCompositeDefaultProps("VkW5vGa1r6")}
                id="HbFirstSlideFooter_VkW5vGa1r6"
                className="__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_VkW5vGa1r6"
              />
            ) : (
              <HbFirstSlideFooterContext.Provider
                key="VkW5vGa1r6-provider"
                value={{
                  key: "VkW5vGa1r6",
                  id: "HbFirstSlideFooter_VkW5vGa1r6",
                  className:
                    "__visly_reset_WDRq65T88Q __visly_scope_2Zvr78cate_VkW5vGa1r6",
                  ...getCompositeDefaultProps("VkW5vGa1r6"),
                }}
              >
                {props.HbFirstSlideFooter}
              </HbFirstSlideFooterContext.Provider>
            )}
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

HbLoadingScreen.HbProgressBar = HbProgressBarComposite;
HbLoadingScreen.HbFirstSlideFooter = HbFirstSlideFooterComposite;
HbLoadingScreen.__variants = [];

export default HbLoadingScreen;
